### ISSUE TITLE
Text reply suggestion

### ISSUE THREAD

**Issue by Noitarud** [pR0Ps/LocationShare#50]
•This idea might be considered a privacy hazard because apps do not require permissions to access internet (you would need Netguard to ban that).

Can you have the app reply to SMSs that ask Where am I? (or other passphrase)

When the request is discovered the app could turn on the GPS, wait for a lock, then transmit to the Contact (person in trusted category) that sent it, turn off, log attempt.

The idea useful if you have lost your phone, need to know where children are even if unable to respond…

**Comment by pR0Ps** [comment]
Hi, thanks for the suggestion. I'm not going to implement this feature because I'd like to keep the scope of this project small and focused just on getting and sharing your current location.

For the feature you're suggesting, I've personally used the FOSS [findmydevice](https://gitlab.com/Nulide/findmydevice) app and it seems to work pretty well. It has features like limiting who can locate the device to contacts, ringing/locking the phone, taking pictures, etc.
